{
 "title": "SR Linux Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "NS",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   { "name": "Iface", "query": { "query": "label_values(interface_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Received Routes (#)",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_bgp_total_received_routes{source=~\"$NE\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Interfaces Throughput (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "-rate(gnmic_interfaces_out_octets{source=~\"$NE\",interface_name=~\"$Iface\"}[1m])*8/1000",
     "legendFormat": "out_octets {{source}} {{interface_name}}"
    },
    {
     "expr": "rate(gnmic_interfaces_in_octets{source=~\"$NE\",interface_name=~\"$Iface\"}[1m])*8/1000",
     "legendFormat": "in_octets {{source}} {{interface_name}}"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_cpu_average_1{source=~\"$NE\"}",
     "legendFormat": "cpu average {{source}}"
    }
   ]
  },
  {
   "title": "BGP Peers UP (#)",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_bgp_up_peers{source=~\"$NE\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "gnmic_mem_utilization{source=~\"$NE\"}",
     "legendFormat": "memory utilization {{source}}"
    }
   ]
  }
 ]
}