name: deploy
on:
  workflow_dispatch:

jobs:
  install_containerlab:
    runs-on: 
      - kss
    steps:
      - run: bash -c "$(curl -sL https://get-clab.srlinux.dev)"
  install_gnmic:
    runs-on: 
      - kss
    steps:
      - run: bash -c "$(curl -sL https://get-gnmic.kmrd.dev)"