{
 "title": "gNMIc Compute metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Open File Descriptors (#)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Go Routines (#)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Stack In Use (MB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Alloc (MB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes/1000000",
     "legendFormat": "{{instance}} mem alloc"
    }
   ]
  },
  {
   "title": "Memory malloc MB/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[1m])/1000000"
    }
   ]
  },
  {
   "title": "Go GC duration (ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds*1000",
     "legendFormat": "{{instance}} quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Memory Heap inUse (MB)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory alloc MB/s ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[1m])/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}