{
 "title": "gNMIc gRPC metrics",
 "time": { "from": "now-5h", "to": "now" },
 "panels": [
  {
   "title": "gRPC Server Started",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grpc_server_started_total", "legendFormat": "{{instance}} {{grpc_method}}" }
   ]
  },
  {
   "title": "gRPC Client Msg Rcv/second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_client_msg_received_total[1m])",
     "legendFormat": "{{instance}} {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client Msg Sent/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_client_msg_sent_total[1m])",
     "legendFormat": "{{instance}} {{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client started",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grpc_client_started_total", "legendFormat": "{{instance}} {{grpc_method}}" }
   ]
  }
 ]
}