clab-nanog83-super-spine1:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine11_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.1.0/31
    - name: ethernet-1/2
      admin_state: enable
      description: to_spine12_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.2.0/31
    - name: ethernet-1/3
      admin_state: enable
      description: to_spine21_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.3.0/31
    - name: ethernet-1/4
      admin_state: enable
      description: to_spine22_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.4.0/31
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 30.1.1.1/32

clab-nanog83-super-spine2:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine11_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.1.0/31
    - name: ethernet-1/2
      admin_state: enable
      description: to_spine12_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.2.0/31
    - name: ethernet-1/3
      admin_state: enable
      description: to_spine21_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.3.0/31
    - name: ethernet-1/4
      admin_state: enable
      description: to_spine22_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.4.0/31
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 30.2.1.1/32

clab-nanog83-spine11:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_super_spine1_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.1.1/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_super_spine2_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.1.1/31

    - name: ethernet-1/3
      admin_state: enable
      description: to_leaf11_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.1.1/31

    - name: ethernet-1/4
      admin_state: enable
      description: to_leaf12_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.2.1/31

    - name: ethernet-1/5
      admin_state: enable
      description: to_leaf13_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.3.1/31

    - name: ethernet-1/6
      admin_state: enable
      description: to_leaf14_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.4.1/31

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 20.1.1.1/32

clab-nanog83-spine12:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_super_spine1_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.2.1/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_super_spine2_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.2.1/31

    - name: ethernet-1/3
      admin_state: enable
      description: to_leaf11_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.1.1/31

    - name: ethernet-1/4
      admin_state: enable
      description: to_leaf12_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.2.1/31

    - name: ethernet-1/5
      admin_state: enable
      description: to_leaf13_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.3.1/31

    - name: ethernet-1/6
      admin_state: enable
      description: to_leaf14_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.4.1/31

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 20.2.1.1/32

clab-nanog83-spine21:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_super_spine1_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.3.1/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_super_spine2_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.3.1/31

    - name: ethernet-1/3
      admin_state: enable
      description: to_leaf21_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.5.1/31

    - name: ethernet-1/4
      admin_state: enable
      description: to_leaf22_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.6.1/31

    - name: ethernet-1/5
      admin_state: enable
      description: to_leaf23_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.7.1/31

    - name: ethernet-1/6
      admin_state: enable
      description: to_leaf24_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.8.1/31

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 20.3.1.1/32

clab-nanog83-spine22:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_super_spine1_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 2.1.4.1/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_super_spine2_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 2.2.4.1/31

    - name: ethernet-1/3
      admin_state: enable
      description: to_leaf21_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.5.1/31

    - name: ethernet-1/4
      admin_state: enable
      description: to_leaf22_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.6.1/31

    - name: ethernet-1/5
      admin_state: enable
      description: to_leaf23_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.7.1/31

    - name: ethernet-1/6
      admin_state: enable
      description: to_leaf24_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.8.1/31

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 20.4.1.1/32

clab-nanog83-leaf11:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine11_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.1.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine12_1/3
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.1.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client1
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.1.1.1/32

clab-nanog83-leaf12:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine11_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.2.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine12_1/4
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.2.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client1
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.2.1.1/32

clab-nanog83-leaf13:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine1_1/5
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.3.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine2_1/5
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.3.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client2
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client

    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.3.1.1/32
  
clab-nanog83-leaf14:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine11_1/6
      subinterface:
        - admin_state: enable
          ipv4_address: 1.1.4.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine12_1/6
      subinterface:
        - admin_state: enable
          ipv4_address: 1.2.4.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client2
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client
      
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.4.1.1/32
       
clab-nanog83-leaf21:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine21_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.5.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine22_1/1
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.5.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client3
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client
      
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.5.1.1/32
       
clab-nanog83-leaf22:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine21_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.6.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine22_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.6.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client3
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client
     
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.6.1.1/32
    
clab-nanog83-leaf23:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine21_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.7.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine22_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.7.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client4
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client
          
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.7.1.1/32

clab-nanog83-leaf24:
  interfaces:
    - name: ethernet-1/1
      admin_state: enable
      description: to_spine21_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.3.8.0/31

    - name: ethernet-1/2
      admin_state: enable
      description: to_spine22_1/2
      subinterface:
        - admin_state: enable
          ipv4_address: 1.4.8.0/31

    - name: ethernet-1/48
      admin_state: enable
      description: to_client4
      # subinterface:
      #   - admin_state: enable
      #     ipv4_address: # configure IP towards client
      
    - name: lo0
      admin_state: enable
      description: loopback0
      subinterface:
        - admin_state: enable
          ipv4_address: 10.8.1.1/32
