clab-nanog83-super-spine1:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.1.0/31
    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.2.0/31
    - name: ethernet-1/3
      admin-state: enable
      description: to_spine3_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.3.0/31
    - name: ethernet-1/4
      admin-state: enable
      description: to_spine4_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.4.0/31
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 30.1.1.1/32

clab-nanog83-super-spine2:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.1.0/31
    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.2.0/31
    - name: ethernet-1/3
      admin-state: enable
      description: to_spine3_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.3.0/31
    - name: ethernet-1/4
      admin-state: enable
      description: to_spine4_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.4.0/31
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 30.2.1.1/32

clab-nanog83-spine1:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_super_spine1_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.1.1/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_super_spine2_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.1.1/31

    - name: ethernet-1/3
      admin-state: enable
      description: to_leaf1_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.1.1/31

    - name: ethernet-1/4
      admin-state: enable
      description: to_leaf2_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.2.1/31

    - name: ethernet-1/5
      admin-state: enable
      description: to_leaf3_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.3.1/31

    - name: ethernet-1/6
      admin-state: enable
      description: to_leaf4_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.4.1/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 20.1.1.1/32

clab-nanog83-spine2:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_super_spine1_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.2.1/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_super_spine2_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.2.1/31

    - name: ethernet-1/3
      admin-state: enable
      description: to_leaf1_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.1.1/31

    - name: ethernet-1/4
      admin-state: enable
      description: to_leaf2_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.2.1/31

    - name: ethernet-1/5
      admin-state: enable
      description: to_leaf3_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.3.1/31

    - name: ethernet-1/6
      admin-state: enable
      description: to_leaf4_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.4.1/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 20.2.1.1/32

clab-nanog83-spine3:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_super_spine1_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.3.1/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_super_spine2_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.3.1/31

    - name: ethernet-1/3
      admin-state: enable
      description: to_leaf5_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.5.1/31

    - name: ethernet-1/4
      admin-state: enable
      description: to_leaf6_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.6.1/31

    - name: ethernet-1/5
      admin-state: enable
      description: to_leaf7_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.7.1/31

    - name: ethernet-1/6
      admin-state: enable
      description: to_leaf8_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.8.1/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 20.3.1.1/32

clab-nanog83-spine4:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_super_spine1_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 2.1.4.1/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_super_spine2_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 2.2.4.1/31

    - name: ethernet-1/3
      admin-state: enable
      description: to_leaf5_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.5.1/31

    - name: ethernet-1/4
      admin-state: enable
      description: to_leaf6_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.6.1/31

    - name: ethernet-1/5
      admin-state: enable
      description: to_leaf7_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.7.1/31

    - name: ethernet-1/6
      admin-state: enable
      description: to_leaf8_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.8.1/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 20.4.1.1/32

clab-nanog83-leaf1:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.1.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/3
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.1.0/31
    
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.1.1.1/32

clab-nanog83-leaf2:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.2.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/4
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.2.0/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.2.1.1/32

clab-nanog83-leaf3:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/5
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.3.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/5
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.3.0/31
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.3.1.1/32
  
clab-nanog83-leaf4:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine1_1/6
      subinterface:
        - admin-state: enable
          ipv4-address: 1.1.4.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine2_1/6
      subinterface:
        - admin-state: enable
          ipv4-address: 1.2.4.0/31
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.4.1.1/32
       
clab-nanog83-leaf5:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine3_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.5.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine4_1/1
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.5.0/31
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.5.1.1/32
       
clab-nanog83-leaf6:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine3_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.6.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine4_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.6.0/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.6.1.1/32
    
clab-nanog83-leaf7:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine3_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.7.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine4_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.7.0/31
    
    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.7.1.1/32

clab-nanog83-leaf8:
  interfaces:
    - name: ethernet-1/1
      admin-state: enable
      description: to_spine3_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.3.8.0/31

    - name: ethernet-1/2
      admin-state: enable
      description: to_spine4_1/2
      subinterface:
        - admin-state: enable
          ipv4-address: 1.4.8.0/31

    - name: lo0
      admin-state: enable
      description: loopback0
      subinterface:
        - admin-state: enable
          ipv4-address: 10.8.1.1/32
