routing-policy:
  prefix-set:
    - name: super-spines-loopbacks
      prefix: 30.0.0.0/8
      mask-length-range: 8..32
    - name: spines-loopbacks
      prefix: 20.0.0.0/8
      mask-length-range: 8..32
    - name: leaves-loopbacks
      prefix: 10.0.0.0/8
      mask-length-range: 8..32
  policy:
    - name: "export-loopbacks"
      statement:
      - sequence-id: 1
        match:
          prefix-set: super-spines-loopbacks
      - sequence-id: 2
        match:
          prefix-set: spines-loopbacks
      - sequence-id: 3
        match:
          prefix-set: leaves-loopbacks