name: deploy
on:
  workflow_dispatch:

jobs:
  install_containerlab:
    runs-on: 
      - self-hosted
      - kss
    steps:
      - run: bash -c "$(curl -sL https://get-clab.srlinux.dev)"
  install_gnmic:
    runs-on: 
      - self-hosted
      - kss
    steps:
      - run: bash -c "$(curl -sL https://get-gnmic.kmrd.dev)"
  checkout:
    runs-on: 
      - self-hosted
      - kss
    needs:
      - install_containerlab
      - install_gnmic
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: sudo bash run.sh